// Code generated by "go run ./cmd/gen-ts"; DO NOT EDIT.
// Source: github.com/meshcore-cz/meshcore-go/meshpkt

export interface ErrResult { error: string }

export interface HexResult {
  hex: string;
}
export interface Envelope {
  route: string;
  routeCode: number;
  type: string;
  typeCode: number;
  version: number;
  pathHashSize: number;
  hopCount: number;
  hops: string[];
  payloadHex: string;
  isTransport: boolean;
  transportCodes?: [number, number];
}
export interface GroupTextPayload {
  sender: string;
  text: string;
  timestamp: number;
  txtType: number;
  attempt: number;
  channelHash: string;
}
export interface DirectTextPayload {
  destHash: string;
  srcHash: string;
  text: string;
  timestamp: number;
  txtType: number;
  attempt: number;
}
export interface AdvertPayload {
  publicKey: string;
  timestamp: number;
  name: string;
  hasGPS: boolean;
  lat?: number;
  lon?: number;
}
export interface KeypairResult {
  publicKey: string;
  privateKey: string;
}

export interface MeshcoreWasm {
  encodeGroupText(channelName: string, sender: string, text: string): HexResult | ErrResult;
  encodeGroupTextSecret(secret: string, sender: string, text: string): HexResult | ErrResult;
  encodeDirectText(privKey: string, peerPubKey: string, text: string): HexResult | ErrResult;
  encodeRaw(route: number, payloadType: number, version: number, pathHashSize: number, payload: string): HexResult | ErrResult;
  decodeEnvelope(packet: string): Envelope | ErrResult;
  decodeGroupText(payload: string, channelName: string): GroupTextPayload | ErrResult;
  decodeGroupTextSecret(payload: string, secret: string): GroupTextPayload | ErrResult;
  decodeDirectText(payload: string, privKey: string, peerPubKey: string): DirectTextPayload | ErrResult;
  decodeAdvert(payload: string): AdvertPayload | ErrResult;
  generateKeypair(): KeypairResult | ErrResult;
  deriveChannelSecret(channelName: string): HexResult | ErrResult;
  sharedSecret(privKey: string, peerPubKey: string): HexResult | ErrResult;
}

export const meshcoreOpNames = [
  "encodeGroupText",
  "encodeGroupTextSecret",
  "encodeDirectText",
  "encodeRaw",
  "decodeEnvelope",
  "decodeGroupText",
  "decodeGroupTextSecret",
  "decodeDirectText",
  "decodeAdvert",
  "generateKeypair",
  "deriveChannelSecret",
  "sharedSecret",
] as const

export const RouteTypes = [
  { code: 0, label: "TRANSPORT_FLOOD" },
  { code: 1, label: "FLOOD" },
  { code: 2, label: "DIRECT" },
  { code: 3, label: "TRANSPORT_DIRECT" },
] as const

export const PayloadTypes = [
  { code: 0x00, label: "REQ" },
  { code: 0x01, label: "RESPONSE" },
  { code: 0x02, label: "TXT_MSG" },
  { code: 0x03, label: "ACK" },
  { code: 0x04, label: "ADVERT" },
  { code: 0x05, label: "GRP_TXT" },
  { code: 0x06, label: "GRP_DATA" },
  { code: 0x07, label: "ANON_REQ" },
  { code: 0x08, label: "PATH" },
  { code: 0x09, label: "TRACE" },
  { code: 0x0a, label: "MULTIPART" },
  { code: 0x0b, label: "CONTROL" },
  { code: 0x0f, label: "RAW_CUSTOM" },
] as const
